### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by abhayjb** [lolipopshock/notion-safari-extension#1]
![image](https://user-images.githubusercontent.com/13074742/101269012-ae197400-37a4-11eb-8238-61d099941d74.png)

Video to reproduce the error - [we.tl/t-apDXv9vzrg](url)

**Comment by lolipopshock** [comment]
Thanks! I should say this is not an issue about the notion-safari-extension tool, but from another used tool for downloading the website information. Basically the error message says that the [`newspaper3k`](https://newspaper.readthedocs.io/en/latest/) tool fails to download the webpage due to a 404 error. Someone else encountered the same issue, see [here](https://github.com/codelucas/newspaper/issues/444). And you might try to modify [the code](https://github.com/lolipopshock/notion-safari-extension/blob/25fe033fbe0e2e0d9fadf78c538ff7764613a1b3/lib/processor.py#L23) according to [this solution](https://github.com/codelucas/newspaper/issues/444#issuecomment-663164692).

**Comment by abhayjb** [comment]
What I could gather from the solution and change in the code is as follows, am I missing some thing?

```python
def _newspaper3k_extract(link):
    config = Config()
    user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15'
    config.browser_user_agent = user_agent
    url = link.strip()
    page = _Article(url, config=config)
    page.download()
    page.parse()
    print(page.text)
    #article = _Article(link, keep_article_html=True)
    #article.download()
    #article.parse()
    return page
```
I now get this error
![image](https://user-images.githubusercontent.com/13074742/101272647-09f5f400-37c9-11eb-80d4-07f138d29857.png)

**Comment by lolipopshock** [comment]
Thanks. I suppose in your modified `_newspaper3k_extract` function, you did not return anything but just print the `page.text`. You may want to return the extracted `page` : 
```Python
def _newspaper3k_extract(link): 
    config = Config() 
    user_agent = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15' 
    config.browser_user_agent = user_agent 
    url = link.strip() 
    page = _Article(url, config=config) 
    page.download() 
    page.parse() 
    return page #Don't forget this line
``` 

And probably you may want to refer to [this instruction](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting) for inserting code blocks.

**Comment by abhayjb** [comment]
Thank you for the hint. I had the return command in there and It is still throwing the same error. Btw thanks also for pointing me to the code insertion snippet ;)

**Comment by lolipopshock** [comment]
Sorry for the delayed response - I was extremely busy during the past few weeks. I've tried again parsing this website (https://mobile.ant.design ), and it runs smoothly without any bugs - could you try again? 

I suppose it's a website's issue, rather than something broken with the tools we are using. But I do think I need to add some error handling in the code when parsing the website for better robustness.
